### ISSUE TITLE
Date should be removed from roadmap page

### ISSUE THREAD

**Issue by TonysCousin** [usdot-fhwa-stol/CARMAPlatform#580]
### Types of Issue

- [ ] Anomaly report (something appears to not work correctly)
- [ ] Enhancement request (describe the enhancement being requested)
- [x] Other (please ensure the description clarifies why the issue doesn’t fall into either of the above categories)

### Descriptive summary
The link on the main github page named "CARMA Roadmap" points to a secondary page in the github repo.  That page then has a link to the actual roadmap, which is published in Confluence.  The indirection page in the repo currently has an "updated on" date, which it doesn't need.  Info on this page is not expected to be updated frequently, only the actual Confluence page is.  When a visitor lands on this page and sees an old "updated on" date, they may conclude that the roadmap is obsolete before they ever see it, and thus avoid looking further.

### Expected behavior
Only the Confluence roadmap page should show an "updated on" date.

### Software version this applies to

n/a

### Actual behavior
The intermediate page, as well as the Confluence roadmap page, shows an extraneous "updated on" date, which is either wrong, or requires unnecessary maintenance effort.

### Steps to reproduce the behavior

1. Go to the main CARMAPlatform github page
2. Follow the link for CARMA Roadmap.

### Related work
None
